#pragma once
#include "TextComponent.h"
#include "FPSComponent.h"
#include "HealthComponent.h"
#include "PointComponent.h"
#include "SubjectComponent.h"
#include "TextureComponent.h"
#include "TransformComponent.h"
#include "SpriteSheetComponent.h"
